# Generated by Django 3.0.4 on 2020-03-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='detail',
            field=models.TextField(),
        ),
    ]
