# Generated by Django 3.0.4 on 2020-05-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200524_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('True', 'New'), ('False', 'Read')], default='new', max_length=10),
        ),
    ]
