# Generated by Django 3.0.4 on 2020-05-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200524_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('False', 'Read'), ('Closed', 'Closed'), ('True', 'New')], default='new', max_length=10),
        ),
    ]
