# Generated by Django 3.0.4 on 2020-05-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200524_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('True', 'New'), ('False', 'Read'), ('Closed', 'Closed')], default='new', max_length=10),
        ),
    ]
