# Generated by Django 3.0.4 on 2020-05-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200524_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('True', 'New'), ('Closed', 'Closed'), ('False', 'Read')], default='new', max_length=10),
        ),
    ]
